import {AbstractControl} from '@angular/forms'

export class AdminPanelValidator
{
    
}


//BREAK THESE UP INTO SEPERATE REQUEST
//GET THE THE CURRENT USER, MOCK THIS
//VALIDATE THE OLD PASSWORD AGAINST WHAT THE SERVER RETURNED
//RESOLVE THE PROMISE BY UPDATING THE PASSWORDS
//SPINKLE SALT WITH AN ENCRYPTION IF YOUR HEART SO DESIRES